# Generated by Django 6.0.8 on 2026-08-09 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0002_library_content_type'),
        ('media', '0003_mediaitem_semantic_key_mediaitem_semantic_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default', max_length=255)),
                ('edition', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_version', to='media.mediafile')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='media.mediaitem')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SemanticMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('unresolved', 'Unresolved'), ('conflict', 'Conflict'), ('manual', 'Manual')], db_index=True, default='unresolved', max_length=32)),
                ('source', models.CharField(blank=True, choices=[('nfo', 'NFO'), ('filename', 'Filename'), ('folder', 'Folder Structure'), ('manual', 'Manual')], max_length=32)),
                ('confidence', models.FloatField(default=0)),
                ('candidate_data', models.JSONField(blank=True, default=dict)),
                ('locked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('last_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_match', to='media.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('sort_title', models.CharField(blank=True, max_length=1024)),
                ('semantic_key', models.CharField(max_length=1024)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('canonical_metadata', models.JSONField(blank=True, default=dict)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='libraries.library')),
            ],
            options={
                'ordering': ['sort_title', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('description', models.TextField(blank=True)),
                ('canonical_metadata', models.JSONField(blank=True, default=dict)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='catalog.series')),
            ],
            options={
                'ordering': ['season_number'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.IntegerField()),
                ('episode_end_number', models.IntegerField(blank=True, null=True)),
                ('absolute_number', models.IntegerField(blank=True, null=True)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='media.mediaitem')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='catalog.season')),
            ],
            options={
                'ordering': ['episode_number'],
                'constraints': [models.UniqueConstraint(fields=('season', 'episode_number'), name='unique_season_episode_number')],
            },
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(fields=('library', 'semantic_key'), name='unique_library_series_semantic_key'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('series', 'season_number'), name='unique_series_season_number'),
        ),
    ]
