# Generated by Django 6.0.8 on 2026-08-09 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('media', '0004_mediaitem_content_rating_mediaitem_external_ids_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalFieldState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('media_item', 'Media Item'), ('series', 'Series'), ('season', 'Season'), ('episode', 'Episode'), ('media_version', 'Media Version')], db_index=True, max_length=32)),
                ('target_id', models.UUIDField(db_index=True)),
                ('field_name', models.CharField(max_length=128)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('nfo', 'NFO'), ('filename', 'Filename'), ('folder', 'Folder Structure'), ('ffprobe', 'ffprobe'), ('embedded', 'Embedded Tags'), ('tubearchivist', 'TubeArchivist'), ('yt_dlp', 'yt-dlp'), ('system', 'System')], default='system', max_length=32)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('value_snapshot', models.JSONField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['field_name'],
            },
        ),
        migrations.CreateModel(
            name='MetadataChangeSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('media_item', 'Media Item'), ('series', 'Series'), ('season', 'Season'), ('episode', 'Episode'), ('media_version', 'Media Version')], db_index=True, max_length=32)),
                ('target_id', models.UUIDField(db_index=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('system', 'System')], default='manual', max_length=32)),
                ('changes', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='external_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mediaversion',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='season',
            name='external_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='series',
            name='content_rating',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='series',
            name='external_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='series',
            name='original_title',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='series',
            name='studios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='series',
            name='tagline',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='mediaversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('media_item',), name='unique_primary_media_version'),
        ),
        migrations.AddField(
            model_name='canonicalfieldstate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_field_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metadatachangeset',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadata_change_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='canonicalfieldstate',
            index=models.Index(fields=['target_type', 'target_id'], name='catalog_can_target__bf1f4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='canonicalfieldstate',
            constraint=models.UniqueConstraint(fields=('target_type', 'target_id', 'field_name'), name='unique_canonical_field_state'),
        ),
        migrations.AddIndex(
            model_name='metadatachangeset',
            index=models.Index(fields=['target_type', 'target_id', 'created_at'], name='catalog_met_target__8fed92_idx'),
        ),
    ]
