# Generated by Django 6.0.8 on 2026-08-10 04:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_canonicalfieldstate_metadatachangeset_and_more'),
        ('libraries', '0002_library_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('media_item', 'Media Item'), ('series', 'Series'), ('season', 'Season'), ('episode', 'Episode')], db_index=True, max_length=32)),
                ('target_id', models.UUIDField(db_index=True)),
                ('artwork_type', models.CharField(choices=[('primary', 'Primary'), ('backdrop', 'Backdrop'), ('banner', 'Banner'), ('logo', 'Logo'), ('thumb', 'Thumb')], db_index=True, max_length=32)),
                ('source_name', models.CharField(blank=True, default='', max_length=64)),
                ('relative_path', models.TextField()),
                ('file_name', models.TextField()),
                ('extension', models.CharField(blank=True, default='', max_length=16)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('modified_ns', models.BigIntegerField(default=0)),
                ('is_selected', models.BooleanField(db_index=True, default=False)),
                ('is_present', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_files', to='libraries.library')),
            ],
            options={
                'ordering': ['target_type', 'target_id', 'artwork_type', 'relative_path'],
                'indexes': [models.Index(fields=['library', 'is_present'], name='catalog_art_library_49aceb_idx'), models.Index(fields=['target_type', 'target_id', 'artwork_type'], name='catalog_art_target__336456_idx')],
                'constraints': [models.UniqueConstraint(fields=('library', 'relative_path'), name='unique_library_artwork_path'), models.UniqueConstraint(condition=models.Q(('is_present', True), ('is_selected', True)), fields=('library', 'target_type', 'target_id', 'artwork_type'), name='unique_selected_target_artwork')],
            },
        ),
    ]
