# Generated by Django 6.0.8 on 2026-08-11 02:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_artworkfile'),
        ('libraries', '0002_library_content_type'),
        ('media', '0004_mediaitem_content_rating_mediaitem_external_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonicalfieldstate',
            name='target_type',
            field=models.CharField(choices=[('media_item', 'Media Item'), ('series', 'Series'), ('season', 'Season'), ('episode', 'Episode'), ('media_version', 'Media Version'), ('channel', 'Channel'), ('online_video', 'Online Video'), ('playlist', 'Playlist')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='metadatachangeset',
            name='target_type',
            field=models.CharField(choices=[('media_item', 'Media Item'), ('series', 'Series'), ('season', 'Season'), ('episode', 'Episode'), ('media_version', 'Media Version'), ('channel', 'Channel'), ('online_video', 'Online Video'), ('playlist', 'Playlist')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='semanticmatch',
            name='source',
            field=models.CharField(blank=True, choices=[('nfo', 'NFO'), ('filename', 'Filename'), ('folder', 'Folder Structure'), ('manual', 'Manual'), ('tubearchivist', 'TubeArchivist'), ('yt_dlp', 'yt-dlp')], max_length=32),
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('source_id', models.CharField(max_length=255)),
                ('semantic_key', models.CharField(db_index=True, max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('sort_title', models.CharField(blank=True, default='', max_length=1024)),
                ('handle', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('source_url', models.TextField(blank=True, default='')),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('canonical_metadata', models.JSONField(blank=True, default=dict)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='libraries.library')),
            ],
            options={
                'ordering': ['sort_title', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OnlineVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('source_id', models.CharField(max_length=255)),
                ('source_url', models.TextField(blank=True, default='')),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('video_kind', models.CharField(choices=[('video', 'Video'), ('short', 'Short'), ('stream', 'Stream'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('canonical_metadata', models.JSONField(blank=True, default=dict)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='catalog.channel')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_videos', to='libraries.library')),
                ('media_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_video', to='media.mediaitem')),
            ],
            options={
                'ordering': ['-upload_date', 'source_id'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('source_id', models.CharField(max_length=255)),
                ('semantic_key', models.CharField(db_index=True, max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, default='')),
                ('source_url', models.TextField(blank=True, default='')),
                ('playlist_kind', models.CharField(choices=[('remote', 'Remote'), ('custom', 'Custom'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('canonical_metadata', models.JSONField(blank=True, default=dict)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='catalog.channel')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='libraries.library')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('online_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_memberships', to='catalog.onlinevideo')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='catalog.playlist')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(fields=('library', 'provider', 'source_id'), name='unique_library_channel_source'),
        ),
        migrations.AddConstraint(
            model_name='onlinevideo',
            constraint=models.UniqueConstraint(fields=('library', 'provider', 'source_id'), name='unique_library_online_video_source'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('library', 'provider', 'source_id'), name='unique_library_playlist_source'),
        ),
        migrations.AddConstraint(
            model_name='playlistmembership',
            constraint=models.UniqueConstraint(fields=('playlist', 'online_video'), name='unique_playlist_online_video'),
        ),
    ]
