# Generated by Django 6.0.8 on 2026-08-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_canonicalfieldstate_target_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonicalfieldstate',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('nfo', 'NFO'), ('filename', 'Filename'), ('folder', 'Folder Structure'), ('ffprobe', 'ffprobe'), ('embedded', 'Embedded Tags'), ('tubearchivist', 'TubeArchivist'), ('tubearchivist_path', 'TubeArchivist Path'), ('yt_dlp', 'yt-dlp'), ('system', 'System')], default='system', max_length=32),
        ),
        migrations.AlterField(
            model_name='semanticmatch',
            name='source',
            field=models.CharField(blank=True, choices=[('nfo', 'NFO'), ('filename', 'Filename'), ('folder', 'Folder Structure'), ('manual', 'Manual'), ('tubearchivist', 'TubeArchivist'), ('tubearchivist_path', 'TubeArchivist Path'), ('yt_dlp', 'yt-dlp')], max_length=32),
        ),
    ]
