# Generated by Django 6.0.8 on 2026-08-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_canonicalfieldstate_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkfile',
            name='target_type',
            field=models.CharField(choices=[('media_item', 'Media Item'), ('series', 'Series'), ('season', 'Season'), ('episode', 'Episode'), ('channel', 'Channel'), ('playlist', 'Playlist')], db_index=True, max_length=32),
        ),
    ]
