# Generated by Django 6.0.8 on 2026-08-11 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0002_library_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('encrypted_secrets', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('error', 'Error')], db_index=True, default='unknown', max_length=32)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LibraryIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_links', to='integrations.integrationconnection')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_links', to='libraries.library')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_integration_connection_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='libraryintegration',
            constraint=models.UniqueConstraint(fields=('library', 'connection'), name='unique_library_integration_connection'),
        ),
    ]
