# Generated by Django 6.0.8 on 2026-08-09 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_mediaitem_canonical_metadata_mediaitem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('filename', 'Filename'), ('ffprobe', 'ffprobe'), ('embedded', 'Embedded Tags'), ('tubearchivist', 'TubeArchivist'), ('yt_dlp', 'yt-dlp'), ('nfo', 'NFO')], max_length=32)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('not_detected', 'Not Detected'), ('not_found', 'Not Found'), ('error', 'Error')], max_length=32)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_sources', to='media.mediafile')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_sources', to='media.mediaitem')),
            ],
            options={
                'ordering': ['source_type'],
                'constraints': [models.UniqueConstraint(fields=('media_file', 'source_type'), name='unique_metadata_source_per_media_file')],
            },
        ),
    ]
