# Generated by Django 6.0.8 on 2026-08-09 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
        ('media', '0002_mediaitem_canonical_metadata_mediaitem_description_and_more'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfoFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relative_path', models.TextField()),
                ('file_name', models.TextField()),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('modified_ns', models.BigIntegerField(default=0)),
                ('root_element', models.CharField(blank=True, max_length=64)),
                ('title', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('raw_xml', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('parse_status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('unparsed', 'Unparsed')], default='unparsed', max_length=16)),
                ('parse_error', models.TextField(blank=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('is_present', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfo_files', to='libraries.library')),
                ('media_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfo_files', to='media.mediafile')),
                ('media_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfo_files', to='media.mediaitem')),
            ],
            options={
                'ordering': ['relative_path'],
                'indexes': [models.Index(fields=['library', 'is_present'], name='metadata_nf_library_3b46ed_idx')],
                'constraints': [models.UniqueConstraint(fields=('library', 'relative_path'), name='unique_library_nfo_relative_path')],
            },
        ),
    ]
