# Generated by Django 6.0.8 on 2026-08-09 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('libraries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scanjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'discovering', 'running'])), fields=('library',), name='one_active_scan_per_library'),
        ),
    ]
