# Generated by Django 6.0.8 on 2026-08-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_scanjob_one_active_scan_per_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='nfo_created_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='nfo_updated_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='processed_media_files',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='processed_nfo_files',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='total_media_files',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='total_nfo_files',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
