# Generated by Django 6.0.8 on 2026-08-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='content_type',
            field=models.CharField(choices=[('auto', 'Automatic'), ('movies', 'Movies'), ('tv', 'TV Shows'), ('online_video', 'Online Video'), ('mixed', 'Mixed Media'), ('generic', 'Generic Video')], db_index=True, default='auto', max_length=32),
        ),
    ]
