# Generated by Django 6.0.8 on 2026-08-09 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=1024)),
                ('media_type', models.CharField(choices=[('unknown', 'Unknown'), ('movie', 'Movie'), ('tv_episode', 'TV Episode'), ('online_video', 'Online Video'), ('home_video', 'Home Video'), ('lecture', 'Lecture'), ('podcast_video', 'Podcast Video'), ('recording', 'Recording'), ('music_video', 'Music Video'), ('other', 'Other')], default='unknown', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='libraries.library')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relative_path', models.TextField()),
                ('file_name', models.TextField()),
                ('extension', models.CharField(blank=True, max_length=32)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('modified_ns', models.BigIntegerField(default=0)),
                ('source_modified_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('container_format', models.CharField(blank=True, max_length=255)),
                ('bit_rate', models.BigIntegerField(blank=True, null=True)),
                ('video_codec', models.CharField(blank=True, max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('frame_rate', models.FloatField(blank=True, null=True)),
                ('audio_codec', models.CharField(blank=True, max_length=64)),
                ('audio_channels', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('probe_status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('error', 'Error')], default='pending', max_length=16)),
                ('probe_error', models.TextField(blank=True)),
                ('raw_probe', models.JSONField(blank=True, default=dict)),
                ('is_present', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='libraries.library')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='media.mediaitem')),
            ],
            options={
                'ordering': ['relative_path'],
                'indexes': [models.Index(fields=['library', 'is_present'], name='media_media_library_751ee8_idx')],
                'constraints': [models.UniqueConstraint(fields=('library', 'relative_path'), name='unique_library_relative_path')],
            },
        ),
    ]
