# Generated by Django 6.0.8 on 2026-08-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='canonical_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
