# Generated by Django 6.0.8 on 2026-08-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_library_content_type'),
        ('media', '0002_mediaitem_canonical_metadata_mediaitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='semantic_key',
            field=models.CharField(blank=True, db_index=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='semantic_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('movie', 'Movie'), ('tv_episode', 'TV Episode'), ('online_video', 'Online Video'), ('home_video', 'Home Video'), ('lecture', 'Lecture'), ('podcast_video', 'Podcast Video'), ('recording', 'Recording'), ('music_video', 'Music Video'), ('other', 'Other')], db_index=True, default='unknown', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='mediaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('semantic_key', ''), _negated=True), fields=('library', 'media_type', 'semantic_key'), name='unique_library_media_semantic_key'),
        ),
    ]
