# Generated by Django 6.0.8 on 2026-08-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_mediaitem_semantic_key_mediaitem_semantic_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='content_rating',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='external_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='original_title',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='sort_title',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='studios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='tagline',
            field=models.TextField(blank=True, default=''),
        ),
    ]
