# Generated by Django 6.0.8 on 2026-08-09 15:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
        ('media', '0002_mediaitem_canonical_metadata_mediaitem_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(choices=[('jellyfin', 'Jellyfin'), ('emby', 'Emby'), ('kodi', 'Kodi'), ('generic', 'Generic')], max_length=32)),
                ('nfo_root_element', models.CharField(default='movie', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('destination_path', models.TextField()),
                ('link_mode', models.CharField(choices=[('symlink', 'Symbolic Link'), ('hardlink', 'Hardlink'), ('copy', 'Copy')], max_length=16)),
                ('naming_template', models.TextField(default='{channel}/{date} - {title} [{youtube_id}]')),
                ('generate_nfo', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='libraries.library')),
                ('output_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projections', to='outputs.outputprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_media_path', models.TextField()),
                ('destination_nfo_path', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('exists', 'Already Exists'), ('error', 'Error')], max_length=16)),
                ('error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projection_items', to='media.mediafile')),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outputs.projection')),
            ],
        ),
        migrations.AddConstraint(
            model_name='outputprofile',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_output_profile_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='projectionitem',
            constraint=models.UniqueConstraint(fields=('projection', 'media_file'), name='unique_projection_media_file'),
        ),
    ]
